In [1]:
import h5py
import numpy as np
import pandas as pd

In [2]:
fName = '/Users/yuntse/data/lartpc_rd/gampix/g4/radiologicals/fullgeoanatruth-vd-reduced_g4_00.h5'

In [3]:
with h5py.File(fName, 'r') as f:
    # Print all top-level groups/datasets
    print(list(f.keys()))
    fS = f['segments']
    fT = f['trajectories']
    fV = f['vertices']
    print(fS.dtype)
    print(fT.dtype)
    print(fV.dtype)
    
    tempS = fS[()]
    tempT = fT[()]
    tempV = fV[()]

['segments', 'trajectories', 'vertices']
{'names': ['event_id', 'vertex_id', 'file_vertex_id', 'segment_id', 'z_end', 'traj_id', 'file_traj_id', 'tran_diff', 'z_start', 'x_end', 'y_end', 'n_electrons', 'pdg_id', 'x_start', 'y_start', 't_start', 't0_start', 't0_end', 't0', 'dx', 'long_diff', 'pixel_plane', 't_end', 'dEdx', 'dE2dx', 'dE', 'dE2', 't', 'y', 'x', 'z', 'n_photons'], 'formats': ['<u4', '<u8', '<u8', '<u4', '<f4', '<i4', '<u4', '<f4', '<f4', '<f4', '<f4', '<u4', '<i4', '<f4', '<f4', '<f4', '<f8', '<f8', '<f8', '<f4', '<f4', '<i4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4'], 'offsets': [0, 8, 16, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 80, 88, 96, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152], 'itemsize': 160}
{'names': ['event_id', 'vertex_id', 'file_vertex_id', 'traj_id', 'file_traj_id', 'parent_id', 'primary', 'E_start', 'pxyz_start', 'xyz_start', 't_start', 'E_end', 'pxyz_end', 'xyz_end', 't_end', 'pdg_id', 'start_process', 'start_subprocess', 'end_process', 'end_subprocess', 'dist_travel'], 'formats': ['<u4', '<u8', '<u8', '<i4', '<u4', '<i4', '?', '<f4', ('<f4', (3,)), ('<f4', (3,)), '<f8', '<f4', ('<f4', (3,)), ('<f4', (3,)), '<f8', '<i4', '<i4', '<i4', '<i4', '<i4', '<f4'], 'offsets': [0, 8, 16, 24, 28, 32, 36, 40, 44, 56, 72, 80, 84, 96, 112, 120, 124, 128, 132, 136, 140], 'itemsize': 144}
{'names': ['event_id', 'vertex_id', 'file_vertex_id', 'x_vert', 'y_vert', 'z_vert', 't_vert', 't_event'], 'formats': ['<u4', '<u8', '<u8', '<f4', '<f4', '<f4', '<f4', '<f4'], 'offsets': [0, 8, 16, 24, 28, 32, 36, 40], 'itemsize': 48}

In [4]:
dS = pd.DataFrame(tempS)
dS

,event_id,vertex_id,file_vertex_id,segment_id,z_end,traj_id,file_traj_id,tran_diff,z_start,x_end,...,t_end,dEdx,dE2dx,dE,dE2,t,y,x,z,n_photons
0,0,2166,2166,0,98.670486,2166,2166,0.0,98.706284,348.101868,...,0.0,0.063558,0.0,0.003178,0.0,0.0,-438.227661,348.086365,98.688385,0.0
1,0,2166,2166,1,98.668915,2168,2168,0.0,98.670486,348.104218,...,0.0,27.031174,0.0,0.089725,0.0,0.0,-438.236572,348.103027,98.669701,0.0
2,0,2166,2166,2,104.624596,2167,2167,0.0,104.624336,342.946564,...,0.0,50.987686,0.0,0.038659,0.0,0.0,-435.562378,342.946808,104.624466,0.0
3,0,2165,2165,3,283.540466,2165,2165,0.0,283.542053,349.946442,...,0.0,0.063542,0.0,0.003178,0.0,0.0,-332.630402,349.921570,283.541260,0.0
4,0,2165,2165,4,283.536835,2170,2170,0.0,283.540466,349.951935,...,0.0,20.367743,0.0,0.134589,0.0,0.0,-332.627686,349.949188,283.538635,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8835149,999,3,2090281,8835149,98.972160,3,7541269,0.0,98.977150,-118.376740,...,0.0,21.503775,0.0,0.124119,0.0,0.0,-469.179474,-118.378151,98.974655,0.0
8835150,999,2,2090280,8835150,112.352966,2,7541268,0.0,112.353348,-321.522552,...,0.0,26.071560,0.0,0.095099,0.0,0.0,-448.416565,-321.521240,112.353157,0.0
8835151,999,1,2090279,8835151,43.172062,1,7541267,0.0,43.163631,111.662086,...,0.0,16.500298,0.0,0.185769,0.0,0.0,-398.363098,111.664001,43.167847,0.0
8835152,999,1,2090279,8835152,43.172062,1,7541267,0.0,43.172062,111.662086,...,0.0,0.000000,0.0,0.000002,0.0,0.0,-398.366302,111.662086,43.172062,0.0
8835153,999,0,2090278,8835153,182.199310,0,7541266,0.0,182.205063,-275.350006,...,0.0,20.716364,0.0,0.131135,0.0,0.0,-528.239075,-275.351013,182.202179,0.0

In [5]:
tempS

array([(0, 0,   0,    0, 1113.1189, 0,    0, 0., 1113.1158 , -309.1597 , -26.063034, 0, 11, -309.16055, -26.065691, 0.,  3679.10343409,  3679.10343434,  3679.10343421, 0.00413554, 0., 0, 0., 24.89521 , 0.10295515, 0., -26.064362, -309.16013, 1113.1174 , 0.),
       (0, 0,   1,    1, 1103.6936, 0,    1, 0., 1103.6782 , -395.9684 , 146.62807 , 0, 11, -395.96332, 146.6412  , 0.,  3642.34775305,  3642.34775397,  3642.34775351, 0.02086017, 0., 0, 0., 13.062375, 0.27248338, 0., 146.63464 , -395.96588, 1103.6859 , 0.),
       (0, 0,   2,    2, 1062.6746, 0,    2, 0., 1062.677  ,  268.65018, 127.29693 , 0, 11,  268.648  , 127.29804 , 0., -1905.68438172, -1905.68438151, -1905.68438161, 0.00344906, 0., 0, 0., 26.65431 , 0.09193232, 0., 127.297485,  268.6491 , 1062.6758 , 0.),
       ...,
       (0, 0, 997, 1188,  901.6404, 0, 1173, 0.,  901.6396 , -328.528  , -99.65973 , 0, 11, -328.52893, -99.65987 , 0.,  2647.58646488,  2647.58646498,  2647.58646493, 0.00121927, 0., 0, 0., 41.453945, 0.05054362, 0., -99.6598  , -328.52847,  901.64   , 0.),
       (0, 0, 998, 1189,  907.1188, 0, 1174, 0.,  907.13153, -327.9765 , -57.453762, 0, 11, -327.935  , -57.44616 , 0.,  1965.7561183 ,  1965.75612029,  1965.7561193 , 0.0440806 , 0., 0, 0., 10.006893, 0.4411099 , 0., -57.44996 , -327.95575,  907.1251 , 0.),
       (0, 0, 999, 1190,  916.6389, 0, 1175, 0.,  916.6388 , -328.6856 , 118.072556, 0, 11, -328.68225, 118.0735  , 0., -2252.78764963, -2252.78764941, -2252.78764952, 0.00348983, 0., 0, 0., 26.377737, 0.09205379, 0., 118.07303 , -328.68393,  916.63885, 0.)],
      dtype={'names': ['event_id', 'vertex_id', 'file_vertex_id', 'segment_id', 'z_end', 'traj_id', 'file_traj_id', 'tran_diff', 'z_start', 'x_end', 'y_end', 'n_electrons', 'pdg_id', 'x_start', 'y_start', 't_start', 't0_start', 't0_end', 't0', 'dx', 'long_diff', 'pixel_plane', 't_end', 'dEdx', 'dE', 't', 'y', 'x', 'z', 'n_photons'], 'formats': ['<u4', '<u8', '<u8', '<u4', '<f4', '<i4', '<u4', '<f4', '<f4', '<f4', '<f4', '<u4', '<i4', '<f4', '<f4', '<f4', '<f8', '<f8', '<f8', '<f4', '<f4', '<i4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4', '<f4'], 'offsets': [0, 8, 16, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 80, 88, 96, 104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144], 'itemsize': 152})

Pandas version 2 will not implicitly accept columns containing arrays (like the vectors in the `trajectories` data).
We need to convert explicitly all the columns that have an array structure (`ndim > 1`) while we can use directly all the others:

In [5]:
dT = pd.DataFrame({
    name: tempT[name].tolist() if tempT[name].ndim > 1 else tempT[name]
    for name in tempT.dtype.names
})

In [6]:
dT

,event_id,vertex_id,file_vertex_id,traj_id,file_traj_id,parent_id,primary,E_start,pxyz_start,xyz_start,...,E_end,pxyz_end,xyz_end,t_end,pdg_id,start_process,start_subprocess,end_process,end_subprocess,dist_travel
0,0,0,0,0,0,-1,True,0.613954,"[0.0682862177491188, 0.21526359021663666, 0.25...","[-309.1605529785156, -476.0657043457031, 217.1...",...,5.109989e-01,"[0.0, 0.0, 0.0]","[-309.1596984863281, -476.06304931640625, 217....",3679.103434,11,0,0,2,22,0.004200
1,0,1,1,1,1,-1,True,0.783480,"[-0.14507721364498138, -0.3742099404335022, 0....","[-395.96331787109375, -303.3587951660156, 207....",...,5.109989e-01,"[-0.0, -0.0, 0.0]","[-395.9684143066406, -303.3719482421875, 207.7...",3642.347754,11,0,0,2,22,0.020858
2,0,2,2,2,2,-1,True,0.602932,"[0.20221948623657227, -0.10365697741508484, -0...","[268.64801025390625, -322.70196533203125, 166....",...,5.109989e-01,"[0.0, -0.0, -0.0]","[268.6501770019531, -322.70306396484375, 166.7...",-1905.684382,11,0,0,2,22,0.003460
3,0,3,3,3,3,-1,True,0.521306,"[0.0872962549328804, -0.05471504479646683, 0.0...","[322.6557312011719, -537.9793701171875, 160.86...",...,5.109989e-01,"[0.0, -0.0, 0.0]","[322.6557922363281, -537.9794311523438, 160.86...",1677.721441,11,0,0,2,22,0.000075
4,0,4,4,4,4,-1,True,0.865161,"[0.3376385569572449, 0.569568395614624, -0.221...","[13.577383995056152, -400.68133544921875, 281....",...,5.109989e-01,"[-0.0, -0.0, -0.0]","[13.591582298278809, -400.6563720703125, 281.4...",2562.904210,11,0,0,2,22,0.030670
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7548703,999,191,2090469,7435,7548701,7434,False,0.514809,"[-0.0542638786137104, 0.03071199730038643, -0....","[102.88733673095703, -379.7540588378906, 23.62...",...,5.109989e-01,"[-0.0, 0.0, -0.0]","[102.88732147216797, -379.7540588378906, 23.62...",-3276.695224,11,2,13,2,22,0.000014
7548704,999,100,2090378,7438,7548704,100,False,0.043357,"[0.010475470684468746, -0.03415379300713539, -...","[-361.52630615234375, -532.1318969726562, 77.7...",...,2.724530e-10,"[0.0, -0.0, -0.0]","[-361.3182678222656, -532.8101196289062, 77.29...",3215.941250,22,2,3,2,12,0.861045
7548705,999,100,2090378,7439,7548705,7438,False,0.551179,"[0.17313790321350098, 0.003298957599326968, -0...","[-361.3182678222656, -532.8101196289062, 77.29...",...,5.109989e-01,"[0.0, 0.0, -0.0]","[-361.3175964355469, -532.8101196289062, 77.29...",3215.941250,11,2,12,2,22,0.000818
7548706,999,16,2090294,7440,7548706,16,False,0.035768,"[0.011605100706219673, 0.031429555267095566, 0...","[-212.93902587890625, -300.22705078125, 130.42...",...,4.693000e-10,"[0.0, 0.0, 0.0]","[-212.8580322265625, -300.0076904296875, 130.5...",3315.841923,22,2,3,2,12,0.249628
7548707,999,16,2090294,7441,7548707,7440,False,0.543590,"[-0.14260771870613098, -0.08196704089641571, 0...","[-212.8580322265625, -300.0076904296875, 130.5...",...,5.109989e-01,"[-0.0, -0.0, 0.0]","[-212.85845947265625, -300.0079345703125, 130....",3315.841923,11,2,12,2,22,0.000567

In [7]:
dV = pd.DataFrame(tempV)
dV

,event_id,vertex_id,file_vertex_id,x_vert,y_vert,z_vert,t_vert,t_event
0,0,0,0,-309.160553,-476.065704,217.175781,3679.103516,0.0
1,0,1,1,-395.963318,-303.358795,207.738235,3642.347656,0.0
2,0,2,2,268.648010,-322.701965,166.737061,-1905.684326,0.0
3,0,3,3,322.655731,-537.979370,160.863037,1677.721436,0.0
4,0,4,4,13.577384,-400.681335,281.481567,2562.904297,0.0
...,...,...,...,...,...,...,...,...
2092310,999,2032,2092310,349.731873,-460.436584,118.624779,400.154144,0.0
2092311,999,2033,2092311,349.925446,-432.601776,106.731682,4207.792480,0.0
2092312,999,2034,2092312,350.203491,-566.271790,91.697006,-1300.933960,0.0
2092313,999,2035,2092313,350.461578,-493.874176,168.746475,2928.797607,0.0
2092314,999,2036,2092314,350.448761,-362.748474,14.822177,-526.222473,0.0

In [8]:
dV[(dV.event_id>10)&(dV.event_id<20)]

,event_id,vertex_id,file_vertex_id,x_vert,y_vert,z_vert,t_vert,t_event
22876,11,0,22876,289.803558,-519.924377,82.490601,1994.720215,0.0
22877,11,1,22877,158.306549,-373.893768,169.618530,-765.302246,0.0
22878,11,2,22878,280.449493,-551.335449,263.574554,4200.213867,0.0
22879,11,3,22879,-325.894745,-479.339905,204.750092,2236.017334,0.0
22880,11,4,22880,-2.927643,-335.840454,98.004379,-1737.397949,0.0
...,...,...,...,...,...,...,...,...
41835,19,2130,41835,350.337860,-536.933289,84.382729,143.762878,0.0
41836,19,2131,41836,350.446533,-392.596558,268.510071,-3646.201660,0.0
41837,19,2132,41837,349.927307,-583.837524,253.263763,3681.494873,0.0
41838,19,2133,41838,349.533844,-559.606506,114.182930,3800.250244,0.0
41839,19,2134,41839,349.694946,-445.122162,296.515503,-1489.398560,0.0

In [9]:
dT[(dT.event_id==15)]

,event_id,vertex_id,file_vertex_id,traj_id,file_traj_id,parent_id,primary,E_start,pxyz_start,xyz_start,...,E_end,pxyz_end,xyz_end,t_end,pdg_id,start_process,start_subprocess,end_process,end_subprocess,dist_travel
114076,15,0,31348,0,114076,-1,True,0.900057,"[-0.627922534942627, 0.3746427595615387, 0.119...","[-222.40286254882812, -494.6072692871094, 92.1...",...,0.510999,"[-0.0, -0.0, 0.0]","[-222.427734375, -494.5945129394531, 92.129409...",3625.488819,11,2,12,2,22,3.106531e-02
114077,15,1,31349,1,114077,-1,True,0.512855,"[-0.015088577754795551, -0.028653372079133987,...","[51.52518081665039, -448.9446105957031, 215.85...",...,0.510999,"[-0.0, -0.0, 0.0]","[51.52518081665039, -448.9446105957031, 215.85...",-1706.929713,11,2,22,2,22,4.622460e-06
114078,15,2,31350,2,114078,-1,True,0.761978,"[0.1627131849527359, 0.2605040967464447, -0.47...","[-164.86085510253906, -344.97869873046875, 198...",...,0.510999,"[0.0, 0.0, -0.0]","[-164.8555908203125, -344.97027587890625, 198....",2420.254291,11,2,22,2,22,1.831040e-02
114079,15,3,31351,3,114079,-1,True,0.753250,"[0.1529615819454193, -0.4122423231601715, 0.33...","[-129.64984130859375, -595.9417114257812, 49.7...",...,0.510999,"[0.0, -0.0, 0.0]","[-129.6450653076172, -595.95458984375, 49.7293...",-2758.801936,11,2,22,2,22,1.730623e-02
114080,15,4,31352,4,114080,-1,True,0.756133,"[0.01796325109899044, 0.5569117665290833, 0.01...","[-5.168187141418457, -597.390869140625, 117.96...",...,0.510999,"[0.0, 0.0, 0.0]","[-5.167619228363037, -597.3732299804688, 117.9...",3249.456943,11,2,2,2,22,1.763593e-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
121820,15,0,31348,7746,121822,7741,False,0.511598,"[0.008453183807432652, 0.02304934896528721, -0...","[-206.832275390625, -508.02020263671875, 101.5...",...,0.510999,"[0.0, 0.0, -0.0]","[-206.832275390625, -508.02020263671875, 101.5...",3625.489852,11,2,13,2,22,9.323539e-07
121821,15,0,31348,7745,121821,7741,False,0.537646,"[-0.09415550529956818, 0.09225153177976608, -0...","[-220.12814331054688, -505.13397216796875, 99....",...,0.510999,"[-0.0, 0.0, -0.0]","[-220.1283721923828, -505.1337585449219, 99.51...",3625.489393,11,2,13,2,22,3.975690e-04
121822,15,0,31348,7744,121820,7741,False,0.585337,"[0.09030799567699432, -0.2346196174621582, 0.1...","[-220.01959228515625, -506.2301025390625, 100....",...,0.510999,"[0.0, -0.0, 0.0]","[-220.01882934570312, -506.2320556640625, 100....",3625.489333,11,2,13,2,22,2.398720e-03
121823,15,0,31348,7743,121819,7741,False,0.519518,"[-0.03686770051717758, 0.020589368417859077, 0...","[-220.2769012451172, -505.73065185546875, 100....",...,0.510999,"[-0.0, 0.0, 0.0]","[-220.27691650390625, -505.73065185546875, 100...",3625.489314,11,2,13,2,22,5.430976e-05
121824,15,0,31348,7742,121818,7741,False,0.534991,"[-0.12794731557369232, -0.056611206382513046, ...","[-223.27313232421875, -496.6974182128906, 92.6...",...,0.510999,"[-0.0, -0.0, -0.0]","[-223.27340698242188, -496.6975402832031, 92.6...",3625.488897,11,2,13,2,22,3.300376e-04

In [10]:
dT[(dT.event_id==31)]

,event_id,vertex_id,file_vertex_id,traj_id,file_traj_id,parent_id,primary,E_start,pxyz_start,xyz_start,...,E_end,pxyz_end,xyz_end,t_end,pdg_id,start_process,start_subprocess,end_process,end_subprocess,dist_travel
234033,31,0,64783,0,234033,-1,True,0.567104,"[0.07777775824069977, -0.15690827369689941, -0...","[212.90550231933594, -354.6929931640625, 153.7...",...,5.109989e-01,"[0.0, -0.0, -0.0]","[212.9059600830078, -354.69390869140625, 153.7...",-4001.910806,11,2,22,2,22,0.001471
234034,31,1,64784,1,234034,-1,True,0.582609,"[-0.1939186304807663, 0.19387665390968323, 0.0...","[198.4380340576172, -460.1163635253906, 163.39...",...,5.109989e-01,"[-0.0, 0.0, 0.0]","[198.4364776611328, -460.11480712890625, 163.3...",-2668.874949,11,2,22,2,22,0.002248
234035,31,2,64785,2,234035,-1,True,0.686871,"[-0.3074091374874115, -0.10366909205913544, 0....","[43.85993194580078, -599.256591796875, 227.091...",...,5.109989e-01,"[-0.0, -0.0, 0.0]","[43.853031158447266, -599.2589111328125, 227.0...",3928.989172,11,2,13,2,22,0.010305
234036,31,3,64786,3,234036,-1,True,0.578604,"[-0.24858932197093964, 0.03886614367365837, -0...","[69.70361328125, -505.315185546875, 190.161254...",...,5.109989e-01,"[-0.0, 0.0, -0.0]","[69.70174407958984, -505.31488037109375, 190.1...",-3987.047016,11,2,13,2,22,0.002035
234037,31,4,64787,4,234037,-1,True,0.532365,"[-0.05878046527504921, -0.1184743195772171, -0...","[-312.724609375, -413.98431396484375, 204.0585...",...,5.109989e-01,"[-0.0, -0.0, -0.0]","[-312.7247314453125, -413.9845275878906, 204.0...",-3466.432899,11,2,22,2,22,0.000269
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
241721,31,129,64912,7687,241720,7686,False,0.522432,"[0.07721946388483047, 0.0664064958691597, 0.03...","[-318.56427001953125, -546.465087890625, 166.3...",...,5.109989e-01,"[0.0, 0.0, 0.0]","[-318.564208984375, -546.4650268554688, 166.32...",367.094368,11,2,13,2,22,0.000090
241722,31,99,64882,7689,241722,99,False,0.014892,"[-0.01024237647652626, 0.010644159279763699, -...","[-146.82749938964844, -358.7034912109375, 16.5...",...,1.393096e-10,"[-0.0, 0.0, -0.0]","[-146.85684204101562, -358.6730041503906, 16.5...",-143.209246,22,2,3,2,12,0.042664
241723,31,99,64882,7690,241723,7689,False,0.522714,"[-0.04640805348753929, 0.026361636817455292, -...","[-146.85684204101562, -358.6730041503906, 16.5...",...,5.109989e-01,"[-0.0, 0.0, -0.0]","[-146.85687255859375, -358.6729736328125, 16.5...",-143.209246,11,2,12,2,22,0.000094
241724,31,31,64814,7691,241724,31,False,0.012190,"[0.0011135074310004711, -0.0004996363422833383...","[-218.32992553710938, -435.6753234863281, 163....",...,1.297588e-10,"[0.0, -0.0, -0.0]","[-218.32554626464844, -435.67730712890625, 163...",2966.630521,22,2,3,2,12,0.047996
241725,31,31,64814,7692,241725,7691,False,0.520011,"[0.05641483888030052, -0.07775022834539413, 0....","[-218.32554626464844, -435.67730712890625, 163...",...,5.109989e-01,"[0.0, -0.0, 0.0]","[-218.32550048828125, -435.6773376464844, 163....",2966.630522,11,2,12,2,22,0.000060

In [11]:
dS[(dS.event_id==15)]

,event_id,vertex_id,file_vertex_id,segment_id,z_end,traj_id,file_traj_id,tran_diff,z_start,x_end,...,t_end,dEdx,dE2dx,dE,dE2,t,y,x,z,n_photons
133515,15,2054,33402,133515,163.536758,2054,116130,0.0,163.583344,357.333893,...,0.0,0.063551,0.0,0.003178,0.0,0.0,-466.955200,357.341461,163.560059,0.0
133516,15,2054,33402,133516,163.536545,2057,116133,0.0,163.536758,357.331726,...,0.0,25.549662,0.0,0.096417,0.0,0.0,-466.958679,357.332825,163.536652,0.0
133517,15,2054,33402,133517,164.445724,2056,116132,0.0,164.445358,357.629730,...,0.0,52.687622,0.0,0.036701,0.0,0.0,-466.764801,357.629456,164.445541,0.0
133518,15,2054,33402,133518,163.925598,2055,116131,0.0,163.924301,349.720856,...,0.0,33.004662,0.0,0.067898,0.0,0.0,-467.562744,349.721558,163.924957,0.0
133519,15,2053,33401,133519,285.434113,2053,116129,0.0,285.470306,344.162384,...,0.0,0.063569,0.0,0.003178,0.0,0.0,-394.278137,344.147797,285.452209,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
142617,15,0,31348,142617,101.503151,7746,121822,0.0,101.503151,-206.832275,...,0.0,0.000000,0.0,0.000599,0.0,0.0,-508.020203,-206.832275,101.503151,0.0
142618,15,0,31348,142618,99.517960,7745,121821,0.0,99.518204,-220.128372,...,0.0,67.118500,0.0,0.026648,0.0,0.0,-505.133850,-220.128265,99.518082,0.0
142619,15,0,31348,142619,100.935425,7744,121820,0.0,100.934288,-220.018829,...,0.0,31.166668,0.0,0.074338,0.0,0.0,-506.231079,-220.019211,100.934860,0.0
142620,15,0,31348,142620,100.797882,7743,121819,0.0,100.797836,-220.276917,...,0.0,176.551056,0.0,0.008519,0.0,0.0,-505.730652,-220.276917,100.797859,0.0
142621,15,0,31348,142621,92.695107,7742,121818,0.0,92.695267,-223.273407,...,0.0,70.440170,0.0,0.023992,0.0,0.0,-496.697479,-223.273270,92.695190,0.0